name: book_app_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  dotenv: ^4.2.0
  postgres: ^3.0.0
  shelf_static: ^1.1.2

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.0.0
  shelf_router_generator: ^1.0.0

assets:
  - .env